openapi: 3.0.0
components:
  schemas:
    Feed:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the feed
        name:
          type: string
          description: The name of the feed
        url:
          type: string
          description: The URL of the feed
        tv:
          type: boolean
          description: Indicates if the feed is a TV feed and should be filtered as such
      required:
        - id
        - name
        - url
    Filter:
      type: object
      properties:
        feedId:
          type: integer
          description: The ID of the feed associated with the filter
        exclude:
          type: array
          items:
            type: string
          description: List of keywords to exclude
        seasonStart:
          type: integer
          description: Minimum season number to include
        episodeStart:
          type: integer
          description: Minimum episode number to include
        showName:
          type: string
          description: Name of the show to filter
      required:
        - feedId
    RSSFeed:
      type: object
      xml:
        name: rss
      properties:
        channel:
          type: object
          properties:
            title:
              type: string
            description:
              type: string
            link:
              type: string
            length:
              type: integer
              description: The number of items in the feed
            item:
              type: array
              items:
                type: object
                properties:
                  title:
                    type: string
                  show_name:
                    type: string
                  link:
                  type: string
                  pubDate:
                    type: string
                    format: date-time
                  season:
                    type: integer
                  episode:
                    type: integer