/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomHeader: typeof import('./src/components/CustomHeader.vue')['default']
    FeedFilters: typeof import('./src/components/manage/FeedFilters.vue')['default']
    FeedForm: typeof import('./src/components/manage/FeedForm.vue')['default']
    FeedList: typeof import('./src/components/FeedList.vue')['default']
    ManageFeed: typeof import('./src/components/ManageFeed.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    NotificationComponent: typeof import('./src/components/NotificationComponent.vue')['default']
    NotificationPopup: typeof import('./src/components/NotificationPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RssView: typeof import('./src/components/manage/RssView.vue')['default']
    ShowRssForm: typeof import('./src/components/manage/ShowRssForm.vue')['default']
    VersionNumber: typeof import('./src/components/header/VersionNumber.vue')['default']
  }
}
