openapi: 3.0.0
info:
  title: RSS Parser API
  version: 1.0.0
  description: API documentation for the RSS Parser project
servers:
  - url: http://localhost:3000
    description: Development server
tags:
  - name: Feeds
    description: Operations related to RSS feeds
  - name: Fetch
    description: Operations related to fetching RSS feeds
components:
  schemas:
    Feed:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the feed
        name:
          type: string
          description: The name of the feed
        url:
          type: string
          description: The URL of the feed
        tv:
          type: boolean
          description: Indicates if the feed is a TV feed and should be filtered as such
      required:
        - id
        - name
        - url
    FeedAddRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the feed
        url:
          type: string
          description: The URL of the feed
        tv:
          type: boolean
          description: Indicates if the feed is a TV feed and should be filtered as such
      required:
        - name
        - url
    FeedEditRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the feed
        url:
          type: string
          description: The URL of the feed
        tv:
          type: boolean
          description: Indicates if the feed is a TV feed and should be filtered as such
    RSSFeed:
      type: object
      xml:
        name: rss
      properties:
        channel:
          type: object
          properties:
            title:
              type: string
            description:
              type: string
            link:
              type: string
            length:
              type: integer
              description: The number of items in the feed
            item:
              type: array
              items:
                type: object
                properties:
                  title:
                    type: string
                  show_name:
                    type: string
                  link:
                    type: string
                  pubDate:
                    type: string
                    format: date-time
                  season:
                    type: integer
                  episode:
                    type: integer

paths:
  /feeds:
    get:
      tags:
        - Feeds
      summary: Retrieve all feeds
      description: Fetches a list of all RSS feeds.
      responses:
        200:
          description: A list of feeds.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feed'
    put:
      tags:
        - Feeds
      summary: Add a new feed or feeds
      description: Adds a new RSS feed to the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FeedAddRequest'
      responses:
        200:
          description: The created feed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feed'
  /feeds/{id}:
    get:
      tags:
        - Feeds
      summary: Retrieve feed by id
      description: Fetches RSS feed by id.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the feed to retrieve.
      responses:
        200:
          description: A given feed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feed'
        404:
          description: Feed not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
                    example: Feed not found
    post:
      tags:
        - Feeds
      summary: Edit feed by id
      description: Edits RSS feed by id.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the feed to edit.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedEditRequest'
      responses:
        200:
          description: The updated feed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feed'
        404:
          description: Feed not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
                    example: Feed not found
    delete:
      tags:
        - Feeds
      summary: Delete feed by id
      description: Deletes RSS feed by id.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the feed to delete.
      responses:
        200:
          description: Feed deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message.
                    example: Feed deleted successfully
  /fetch:
    get:
      tags:
        - Fetch
      summary: Fetch RSS feeds
      description: Fetches RSS feeds from the configured sources and returns them in XML format.
      responses:
        200:
          description: Successfully fetched RSS feeds.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/RSSFeed'
        500:
          description: Error fetching RSS feeds.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
  /fetch/{url}:
    get:
      tags:
        - Fetch
      summary: Test fetch RSS feed by url
      description: Tests fetching of RSS feed from the passed-in sources and returns them in XML format.
      parameters:
        - in: path
          name: url
          required: true
          schema:
            type: string
          description: The URL of the feed to retrieve.
      responses:
        200:
          description: Successfully fetched RSS feed.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/RSSFeed'
        500:
          description: Error fetching RSS feeds.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
