openapi: 3.0.0
info:
  title: RSS Parser API
  version: 1.0.0
  description: API documentation for the RSS Parser project
servers:
  - url: http://localhost:3000/api
    description: Development server
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
security:
  - ApiKeyAuth: []
tags:
  - name: Feeds
    description: Operations related to RSS feeds
  - name: Fetch
    description: Operations related to fetching RSS feeds
  - name: Filters
    description: Operations related to filters
