openapi: 3.0.0
paths:
  /fetch:
    get:
      tags:
        - Fetch
      summary: Fetch RSS feeds
      description: Fetches RSS feeds from the configured sources and returns them in XML format.
      responses:
        200:
          description: Successfully fetched RSS feeds.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/RSSFeed'
        500:
          description: Error fetching RSS feeds.
          content:
            application/json:
              schema:
                $ref: '#/components/responses/ErrorResponse'
    post:
      tags:
        - Fetch
      summary: Test fetch RSS feed by url
      description: Tests fetching of RSS feed from the passed-in sources and returns them in XML format.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: The URL of the feed to retrieve.
                tv:
                  type: boolean
                  description: Whether to filter as TV show or not.
                filter:
                  $ref: '#/components/schemas/Filter'
                  description: The filter to apply to the feed.
            required:
              - url
      responses:
        200:
          description: Successfully fetched RSS feed.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/RSSFeed'
        500:
          description: Error fetching RSS feeds.
          content:
            application/json:
              schema:
                $ref: '#/components/responses/ErrorResponse'
